version: '3'
services:
  media-s3-sync:
    build: .
    container_name: media.s3-sync
    command: bash -c "tail -f /dev/null"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "3010:3010"
    networks:
      infra_cdn:
        aliases:
          - media-s3-sync

networks:
  infra_cdn:
    external: true
