service: media-s3-sync

provider:
  name: aws
  runtime: nodejs8.10

functions:
  post:
    handler: src/handler.post
  remove:
    handler: src/handler.remove
  update:
    handler: src/handler.update
    events:
      - s3:
        bucket: ${env:AWS_S3_BUCKET}
        event: s3:ObjectCreated:*

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: internals/webpack.config.js
